"""add new fields to classrooms table with nullable

Revision ID: 0ed574713567
Revises: 8eb7502deab7
Create Date: 2025-06-17 10:43:22.628786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed574713567'
down_revision: Union[str, None] = '8eb7502deab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('classrooms', sa.Column('building_name', sa.String(), nullable=True))
    op.add_column('classrooms', sa.Column('computers', sa.Integer(), nullable=True))
    op.alter_column('classrooms', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('classrooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_classrooms_short_name'), 'classrooms', ['short_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classrooms_short_name'), table_name='classrooms')
    op.alter_column('classrooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('classrooms', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('classrooms', 'computers')
    op.drop_column('classrooms', 'building_name')
    op.drop_column('classrooms', 'short_name')
    # ### end Alembic commands ###
