"""add fields to groups

Revision ID: 388e69b6cef8
Revises: create_cadre_table
Create Date: 2024-03-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '388e69b6cef8'
down_revision: Union[str, None] = 'dc8077ab752f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('subgroup', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('faculty', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'type')
    op.drop_column('groups', 'faculty')
    op.drop_column('groups', 'subgroup')
    # ### end Alembic commands ###
