"""create cadre table

Revision ID: create_cadre_table
Revises: dc8077ab752f
Create Date: 2025-06-17 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'create_cadre_table'
down_revision: Union[str, None] = 'dc8077ab752f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id2', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('emailAddress', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('facultyName', sa.String(), nullable=True),
    sa.Column('departmentName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cadre_id'), 'cadre', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cadre_id'), table_name='cadre')
    op.drop_table('cadre')
    # ### end Alembic commands ### 